version: 1.0.{build}
branches:
  only:
  - master  
os: Visual Studio 2015

image:
- Visual Studio 2015
- Visual Studio 2017

clone_depth: 1
clone_folder: C:\test_project


environment:
  matrix:
    - compiler: vs2015
      platform: x86
      config: Debug
    - compiler: vs2015
      platform: x86
      config: Release
    - compiler: vs2015
      platform: x64
      config: Debug
    - compiler: vs2015
      platform: x64
      config: Release

install:
- appveyor DownloadFile https://nmap.org/npcap/dist/npcap-sdk-0.1.zip
- 7z x .\npcap-sdk-0.1.zip -o.\libs\

before_build:
- call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
- cd libs\
- ren npcap-sdk-0.1 npcap-sdk
- cd ..

build_script:
- cd src\helloworld
- cl main.cpp
